services:
  - type: web
    name: boost-bot
    runtime: python
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    env: python
    plan: free