name: BoostBot

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Schedule
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
        run: python src/scripts/daily.py

# name: BoostBot

# on:
#   schedule:
#     - cron: '0 */6 **'
#   workflow_dispatch:
    
# jobs:
#   check:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: action/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       - name: Run shedule checker
#         env:
#           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRM_BOT_TOKEN }}
#           DATABASE_URL: ${{ secrets.DATABASE_URL }}
#           DATABASE_SERVICE_KEY: ${{ secrets.DATABASE_SERVICE_KEY }}
#         run: python src/scripts/check_schedule_changes.py